name: Continuous Deployment

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml

  deploy:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: digitalocean/app_action/deploy@cc55bc9b848d25f9c1c9f831cf843fbab3fbfb15
        env:
          REPOSITORY_ROOT_URI: ${{ vars.REPOSITORY_ROOT_URI }}
        with:
          token: ${{ secrets.DIGITALOCEAN_DEPLOYMENT }}
          print_build_logs: true
          print_deploy_logs: true
