name: Check and Test

on:
  workflow_call:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: opensafely-core/setup-action@v1
        with:
          python-version: 3.12
          cache-dependency-path: requirements.*.txt
          install-just: true
      - run: just devenv
      - run: just check

  test:
    needs: check
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: pass
          POSTGRES_DB: jobserver
        ports:
          - 3979:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 10s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: opensafely-core/setup-action@v1
        with:
          python-version: 3.12
          cache-dependency-path: requirements.*.txt
          install-just: true
      - run: just devenv
      - run: just test
